ort: D-51371 Leverkusen
firma: Best Quality Solutions GmbH
adresse: Kieselstraße 6
telefon: +49 (0)173 699 550 6
fax: +49 (0)3212 392 796 7
steuernr: 230/5701/5155
umsatzident: DE354235838
amtsgericht: HRB 110183, Amtsgericht Köln
name: Frank Wollin
email: mail@bqs-gmbh.com
banner_top: Erfolgsfaktor Qualitätsmanagement
banner_head: Grundstein für nachhaltigen Unternehmenserfolg
wir_top: Wer wir sind
wir_head: Unser Ansatz und Expertise
wir_text: QM-Management ist unsere Expertise. Als Basis für nachhaltigen Unternehmenserfolg gewinnen sie einen Wettbewerbsvorteil durch effektivere Prozesse und die Sicherstellung von Qualität und Compliance durch unsere Qualitätsmanagement-Lösungen. 
wir_button: Services
punkt_1_head: Unsere Aufgabe
punkt_1_text: Effektive Prozesse durch das richtige Qualitätsmanagement. Lorem ipsum dolor sit amet lorem ipsum. Lorem ipsum dolor sit amet lorem ipsum dolor.
punkt_2_head: Compliance
punkt_2_text: Sicherstellung von Qualität und Compliance durch unsere Qualitätsmanagement-Lösungen Lorem ipsum dolor sit amet lorem ipsum dolor.
punkt_3_head: Unser Ansatz
punkt_3_text: Qualitätsmanagement als Basis für nachhaltigen Unternehmenserfolg. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet.
zahl_1: 523
zahl_1_text: Zertifizierungen
zahl_2: 253
zahl_2_text: Schulungen
zahl_3: 29
zahl_3_text: Länder
zahl_4: 1
zahl_4_text: Team
ansprechpartner_top: Unser Team
ansprechpartner_head: Direkte Ansprechpartner für ihr Unternehmen
person_1_name: Melinda Maier
person_1_position: Geschäftsführung
person_2_name: Max Mustermann
person_2_position: stellv. Geschäftsführung
zitat_top: Was unsere Partner sagen
zitat_head: Lorem ipsum dolor sit amet
zitat_1_name: Max Mustermann
zitat_1_position: Geschäftsführer Lorem
zitat_1_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit, ducimus lorem ipsum dolor sit amet.
zitat_2_name: Max Mustermann
zitat_2_position: Geschäftsführer Lorem
zitat_2_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit, ducimus lorem ipsum dolor sit amet.
zitat_3_name: Max Mustermann
zitat_3_position: Geschäftsführer Lorem
zitat_3_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit, ducimus lorem ipsum dolor sit amet.
kasten_top: Hilfe benötigt?
kasten_head: Vertrau auf die Hilfe unseres Team
kasten_text: "Haben sie ein Projekt im Sinn? <br /> Für direkten Kontakt :"
service_top: Unser Service
service_head: Die BQS GmbH führt folgende Tätigkeiten aus
icon_1_H: Zertifizierungen 
icon_1_T: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit, ducimus.
icon_2_H: Systematik
icon_2_T: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit, ducimus.
icon_3_H: Schulungen
icon_3_T: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit, ducimus.
icon_4_H: Regulatory Affairs
icon_4_T: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit, ducimus.
icon_5_H: Management
icon_5_T: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit, ducimus.
icon_6_H: Qualität
icon_6_T: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit, ducimus.
icon_7_H: Compliance
icon_7_T: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit, ducimus.
icon_8_H: Grundbaustein
icon_8_T: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit, ducimus.
kontakt_top: Hier sind wir erreichbar
kontakt_head: Weitere Kontaktdaten
