ort: D-51371 Leverkusen
firma: Best Quality Solutions GmbH
adresse: Kieselstraße 6
telefon: +49 (0)173 699 550 6
fax: +49 (0)3212 392 796 7
steuernr: 230/5701/5155
umsatzident: DE354235838
amtsgericht: HRB 110183, Amtsgericht Köln
name: Frank Wollin
email: mail@bqs-gmbh.com
banner_top:  Willkommen bei der BQS GmbH 
banner_head: Ihrem Experten für <br /> Qualitäts- und Zulassungsfragen <br /> in der Medizintechnik
wir_top: Wer wir sind
wir_head: Spezialist für Qualitätsmanagement und Risikomanagement
wir_text: Die BQS GmbH bietet Ihnen passgenaue und skalierbare Lösungen <br /> und Dienstleistungen für alle Ihre Herausforderungen in der Medizintechnik. Mit unserem ausgezeichneten Experten-Know-how und unserer ausgeprägten Hands-on-Mentalität lösen wir effizient und pragmatisch Probleme von der Produktkonzeption über die Produktentwicklung bis zur Serienproduktion, einschließlich der Zulassung und dem Life-Cycle-Engineering.
weiteres_top: Weitere Dienstleistungen
weiteres_head: Umfassende Betreuung in allen Belangen
weiteres_text: Zusätzlich zu unseren Kernkompetenzen bieten wir auch Leistungen in den Bereichen Qualifizierung und Validierung, Risiko-, CAPA –, Projekt -, Änderung - und Lieferantenmanagement, Audits, FMEA-Moderation, Design Transfers und Dokumentationserstellung an, um die Sicherheit und Leistungsfähigkeit von Medizinprodukten zu gewährleisten. <br /> <br /> Des Weiteren unterstützen wir Sie in der Medizintechnikbranche bei der Entwicklung von Risikomanagementplänen gemäß ISO 14971, um Risiken im Zusammenhang mit der Verwendung ihrer Produkte zu identifizieren, zu bewerten und zu kontrollieren, um die Sicherheit für Patienten und Benutzer zu gewährleisten.
wir_button: Dienstleistungen
punkt_1_head: Ganzheitlich
punkt_1_text: Unsere Experten bieten Ihnen maßgeschneiderte Lösungen für alle <br /> Qualitäts- und Zulassungsfragen, <br /> von der Produktkonzeption bis zur Serienproduktion.
punkt_2_head: Kompetent
punkt_2_text: Als Spezialisten für Qualitätsmanagement <br /> und Risikomanagement sind wir vertraut <br /> mit den Normen ISO 13485, <br /> 21 CFR 820 und ISO 14971 sowie den Anforderungen der FDA.
punkt_3_head: Geschult
punkt_3_text: Neben Aufbau und Remediation von Qualitätsmanagementsystemen gemäß ISO 13485 und 21 CFR 820 bieten wir auch interimsweise Qualitätsleitung und Regulatory Affairs-Schulungen an.
zahl_1: 523
zahl_1_text: Zertifizierungen
zahl_2: 253
zahl_2_text: Schulungen
zahl_3: 29
zahl_3_text: Länder
zahl_4: 1
zahl_4_text: Team
ansprechpartner_top: Unser Team
ansprechpartner_head: Direkte Ansprechpartner für ihr Unternehmen
person_1_name: Melinda Maier
person_1_position: Geschäftsführung
person_2_name: Max Mustermann
person_2_position: stellv. Geschäftsführung
zitat_top: Was unsere Partner sagen
zitat_head: Lorem ipsum dolor sit amet
zitat_1_name: Max Mustermann
zitat_1_position: Geschäftsführer Lorem
zitat_1_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit, ducimus lorem ipsum dolor sit amet.
zitat_2_name: Max Mustermann
zitat_2_position: Geschäftsführer Lorem
zitat_2_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit, ducimus lorem ipsum dolor sit amet.
zitat_3_name: Max Mustermann
zitat_3_position: Geschäftsführer Lorem
zitat_3_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit, ducimus lorem ipsum dolor sit amet.
kasten_top: Hilfe benötigt?
kasten_head: Vertrau auf die Hilfe unseres Team
kasten_text: "Haben sie ein Projekt im Sinn? <br /> Für direkten Kontakt :"
service_top: Unser Service
service_head: Maßgeschneiderte Lösungen für die Medizintechnik
icon_1_H: Zertifizierungen 
icon_1_T: Vertraut mit den Normen ISO 13485, 21 CFR 820 und ISO 14971 sowie den Anforderungen der FDA
icon_2_H: Remidation
icon_2_T: Remediation von Qualitätsmanagementsystemen gemäß ISO 13485 und 21 CFR 820
icon_3_H: Reports
icon_3_T: Clinical Evaluation Reports (CER) und Clinical Performance Assessment (CPA) gemäß den Anforderungen der MDR und IVDR.
icon_4_H: Schulungen 
icon_4_T: Qualitätsmanagementsysteme, Interimsleitung und Schulungen für Medizintechnik-Unternehmen
icon_5_H: Dokumentation
icon_5_T: Technische Dokumentationen gemäß MDR und IVDR für Medizinprodukte
icon_6_H: Bewertung
icon_6_T: CER und CPA-Erstellung für die Bewertung von Medizinprodukten
icon_7_H: Six Sigma
icon_7_T: Six Sigma-Methodik zur Prozessoptimierung in der Medizintechnik
icon_8_H: Analyse
icon_8_T: Analyse und Lösungen für Qualitätsmanagement in der Medizintechnik.
icon_9_H: Lieferung
icon_9_T: Projekt-, Änderung- und Lieferantenmanagement, Audits und FMEA-Moderation

kontakt_top: Hier sind wir erreichbar
kontakt_head: Weitere Kontaktdaten
